### ISSUE TITLE
Getting `Metric Request Error` querying AWS Athena

### ISSUE THREAD

**Issue by jfagoagas** [grafana/athena-datasource#104] opened 2021-12-24 11:37 UTC
**What happened**:
I am getting the following error querying AWS Athena with the following query:
`select count(*) from $__table where created_at = '$audit_date' and account_name = '$account_name';`

<img width="1368" alt="Screenshot 2021-12-24 at 12 17 08" src="https://user-images.githubusercontent.com/16007882/147348348-d22b9eaa-f0ed-448c-85de-b44b46b3d071.png">

Also, when I inspect this query, the `Error` tab is showing the following information:
<img width="317" alt="Screenshot 2021-12-24 at 12 27 01" src="https://user-images.githubusercontent.com/16007882/147348969-6ca0b32c-87dc-49ba-aeff-b5c626f8c3a3.png">

As you can inspect I am using two dashboard variables with the following queries:
- `$audit_date`: 
`SELECT DISTINCT created_at AS audit_date FROM "aws_logs"."security_audit_results" WHERE account_name = '$account_name' ORDER BY audit_date DESC LIMIT 1;`
- `$account_name`: 
`SELECT DISTINCT account_name from "aws_logs"."security_audit_results";` 

These queries works fine in AWS Athena console too.

The fun fact is that if I reload this panel everything works fine but when I save/apply it and I return to the dashboard view I still get the previous error:

- When I refresh this panel:
<img width="1371" alt="Screenshot 2021-12-24 at 12 22 30" src="https://user-images.githubusercontent.com/16007882/147348693-9f90c007-1bb9-48b4-a6d9-902a4bf6efa5.png">

- When I return to the dashboard view:
<img width="858" alt="Screenshot 2021-12-24 at 12 23 14" src="https://user-images.githubusercontent.com/16007882/147348732-842f94b5-02aa-44fd-8445-e323f9d39c09.png">

The plugin configuration is the following:
![Screenshot 2021-12-24 at 12 57 13](https://user-images.githubusercontent.com/16007882/147350922-678758dc-4269-4adc-9e67-cb565781e056.png)

**What you expected to happen**:
This panel should show the following information.
<img width="1372" alt="Screenshot 2021-12-24 at 12 28 30" src="https://user-images.githubusercontent.com/16007882/147349049-cd4c2364-590c-4205-b65f-ce44990d65ed.png">

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an empty panel in a dashboard.
2. Select Table visualization.
3. Select Athena Grafana datasource.
4. Configure your Athena region, datasource, database and table.
5. Select format as Table.
6. Introduce some Athena query to recover data.

If I check container's log I can see the following:
```
t=2021-12-24T11:50:56+0000 lvl=eror msg="Metric request error" logger=context userId=42 orgId=1 uname=XXXXXX@XXXXXX.com error="plugin unavailable" remote_addr=XXX.XXX.XXX.XXX

t=2021-12-24T11:50:56+0000 lvl=eror msg="Request Completed" logger=context userId=42 orgId=1 uname=XXXXXX@XXXXXX.com method=POST path=/api/ds/query status=500 remote_addr=XXX.XXX.XXX.XXX time_ms=20 size=34 referer="https://XXXXXX.XXXXXX.com/d/XOC1xyMGp/dashaboard1?orgId=1"

t=2021-12-24T13:19:59+0000 lvl=eror msg="Metric request error" logger=context userId=42 orgId=1 uname=XXXXXX@XXXXXX.com error="failed to query data: Failed to query data: rpc error: code = Unavailable desc = error reading from server: EOF" remote_addr=XXX.XXX.XXX.XXX 
```
**Screenshots**
I have include it above, at the explanation.

**Anything else we need to know?**:
I'm a little bit stuck with this error :sweat:

**Environment**:
- Grafana version: v8.2.3 (fb85ed6912)
- Plugin version: 1.0.1
- OS Grafana is installed on: Docker image "grafana/grafana:8.2.3" at Amazon ECS Service
- User OS & Browser: macOS 12.0.1 & Chrome 96.0.4664.110

**Comment by andresmgot** [comment] 2021-12-24 12:40
Hi @jfagoagas,

I am not able to reproduce your issue locally. I tried:

```
▶ docker run -p 3000:3000 --name=grafana \
  -e "GF_INSTALL_PLUGINS=grafana-athena-datasource" \                         
  grafana/grafana:8.2.3
```

And I am able to create a panel and write a query normally. The issue seems related to this line you reported:

```
t=2021-12-24T11:50:56+0000 lvl=eror msg="Metric request error" logger=context userId=42 orgId=1 uname=XXXXXX@XXXXXX.com error="plugin unavailable" remote_addr=XXX.XXX.XXX.XXX
```

How did you install the plugin? (I am not sure how it's available for some requests but not for others).

Does the problem persist if you restart the container (or grafana)?

**Comment by jfagoagas** [comment] 2021-12-24 12:51
Hi @andresmgot,

Thank you for your fast reply!

> How did you install the plugin? (I am not sure how it's available for some requests but not for others).

I have installed this plugin using Grafana's plugin catalog app.

> Does the problem persist if you restart the container (or grafana)?

I am going to try this now.

**Comment by jfagoagas** [comment] 2021-12-24 13:15
@andresmgot I have restarted Grafana's container and reinstalled Athena's plugin and the errors keep appearing.

**Comment by andresmgot** [comment] 2021-12-24 13:40
I have tried using the plugin catalog and still not able to reproduce it. Some questions:

 - Are you still seeing the `plugin unavailable` error?
 - Are you able to reproduce the issue in other environment (not ECS)? Like a local docker environment.
 - Does it work if you try without the assumed role?
 
Let see if we can narrow down the issue.

**Comment by jfagoagas** [comment] 2021-12-24 16:29
> I have tried using the plugin catalog and still not able to reproduce it. Some questions:
> 
> * Are you still seeing the `plugin unavailable` error?
Yes, I still got it.

> * Are you able to reproduce the issue in other environment (not ECS)? Like a local docker environment.
I'm trying to but I can't, it's really strange.

> * Does it work if you try without the assumed role?
I am trying to set up another environment without the assumed role and it seems to work.

**Comment by jfagoagas** [comment] 2021-12-29 15:05
@sp-aliciaalcalde

**Comment by sarahzinger** [comment] 2022-01-03 19:56
@jfagoagas if you add back the assumed role does it break again? Trying to determine if the issue is related to the environment or the configuration. Thanks for your help!

**Comment by jfagoagas** [comment] 2022-01-03 23:45
Yes, if I configure the assumed role back it breaks.

**Comment by sarahzinger** [comment] 2022-01-05 16:53
@jfagoagas I tried making queries using an athena datasource with an ARN and template variables and was unable to reproduce the issue you are seeing. When you say adding the Assumed Role breaks, what specifically are you seeing breaking? Is it that all queries break or that queries break only on dashboard pages but not in panel pages as you originally described in this issue?

I was able to find other issues where editing a broken or out of date config for an athena datasource did not update properly and used a stale connection which I believe is already a known issue and captured in [this issue](https://github.com/grafana/athena-datasource/issues/105). 

I'm sorry you're having difficulty running your queries but unfortunately without clear repro steps it'll be difficult to debug what you're seeing. If you can narrow down the issue more that would be very helpful! thanks.

**Comment by jfagoagas** [comment] 2022-01-16 08:04
Hi @sarahzinger, thank you for your help and support but I no longer have access to this Grafana's installation.

If I'm being honest, this bug is kind of strange and I don't know if it is related to Grafana itself or to somewhat in AWS.

Also, I haven't been able to reproduce it again.

Thank you!

**Comment by andresmgot** [comment] 2022-01-17 08:26
Thanks for the comment @jfagoagas, let me close the issue then. Please reopen if you can reproduce it again.

**Closed by andresmgot** 2022-01-17 08:26 UTC
Labels: type/bug, datasource/Athena, needs investigation
