### ISSUE TITLE
Athena workgroup showing as '' despite being set in the Datasource

### ISSUE THREAD

**Issue by geolney** [grafana/athena-datasource#308] opened 2024-01-25 17:20 UTC
**What happened**:
When testing Athena connectivity by doing a simple 'SHOW DATABASES' using Athena datasource I am getting shown an error relating to the workgroup variable which appears to be set as nothing ('') when I have set it in the datasource config:

`Status: 500. Message: error executing query: InvalidRequestException: 1 validation error detected: Value '' at 'workGroup' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9._-]{1,128} { RespMetadata: { StatusCode: 400, RequestID: "373c7afe-659f-4597-97c4-adb9207624c9" }, AthenaErrorCode: "INVALID_INPUT", Message_: "1 validation error detected: Value '' at 'workGroup' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9._-]{1,128}" }`.

**What you expected to happen**:
Table names to be returned by the query.

**Screenshots**
Query:
<img width="1721" alt="Screenshot 2024-01-25 at 17 11 59" src="https://github.com/grafana/athena-datasource/assets/75424289/633ea370-af3d-4178-97d9-157b41dccbad">

AWS Athena Datasource config:
<img width="865" alt="Screenshot 2024-01-25 at 17 13 39" src="https://github.com/grafana/athena-datasource/assets/75424289/4b27cef8-2489-423f-8047-bbc1d1b0550b">

**Anything else we need to know?**:

**Environment**:
- Grafana version: v10.2.2
- Plugin version: 2.13.4
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS & Chrome
- Others: EKS 1.25

**Comment by sarahzinger** [comment] 2024-01-26 18:51
hi @geolney I'm sorry to hear that. I'm not 100% what's going on and haven't reproduced it here, but my guess would be that your issues is related to https://github.com/grafana/athena-datasource/issues/305 and that there's something wrong with your auth but our health check is not working properly?

I will bring #305 to the team and see if we can prioritize a fix in the next couple of weeks. In the meantime, can you confirm that those selections work if you try to ping with the aws cli to confirm it's the right credentials? Thank you for your patience!

**Comment by geolney** [comment] 2024-01-29 15:18
Hi @sarahzinger thank you for your response, I shall take a look at the related issue and hopefully will be resolved as part of it! 

In the meantime I did have a bit more info to go by and have a few things to try. In short the situation is this:

- Centralised Grafana on version `10.2.2` in AWS account `X` is reporting that for the Athena in AWS Account `Y` the workgroup value is `''` when it is specified `'primary'` in the datasource and doesn't work despite the credentials allowing it to lookup the table/workgroup name etc and claims is configured/connecting.
- Test sandbox on version `10.0.2` in AWS account `Y` is configured to the same account `Y`'s Athena and shows the same connectivity. This is showing data as expected and I can query to see expected results. 

So the only 2 differences between one working and not working is:
1. One is reading from a different AWS account (albeit with the same Credentials) than the Athena, and the other (working) is in the same.
2. The same one is on version 10.2.2 and the other (working) is on 10.0.2.

So I shall be upgrading to 10.2.2 in the test to see if this causes an issue and then revisiting the configuration. 
Thank you once again for your help!

**Comment by njvrzm** [comment] 2024-02-13 13:00
I just ran into this same issue - weirdly, I'd get the `Value '' at 'workGroup' failed to satisfy constraint` error if I left the `Datasource` and `Database` values in the query editor at their "Default" values, but I got a different error if I chose the same values from the dropdowns. Ultimately I think that was due to missing permissions on the access key. I'll see if I can reproduce it.

**Comment by njvrzm** [comment] 2024-02-27 14:54
@geolney - I've been able to reproduce this and it appears to be the same basic issue as #264 - sometimes the datasource gets saved prematurely with an empty workgroup which is then cached along with the connection. If this is the issue you're having it should be (temporarily) fixed by selecting the datasource and database from the dropdowns rather than leaving them with the "default (foo)" values.

Once the fix for that issue (PR #314) is deployed I'll post an update here and and you can check whether the problem is resolved for you.

**Comment by njvrzm** [comment] 2024-03-13 10:36
Fyi, @geolney, the fix above is released with version [2.13.6](https://github.com/grafana/athena-datasource/releases/tag/v2.13.6). I'm going to close this issue for now, but when you have a chance to try the new release out, please let us know if you run into this issue again.

**Closed by njvrzm** 2024-03-13 10:36 UTC
Labels: type/bug, datasource/Athena
