### ISSUE TITLE
Athena results always in local timezone

### ISSUE THREAD

**Issue by robbierolin** [grafana/athena-datasource#167] opened 2022-07-07 23:33 UTC
**What happened**:
I am seeing that the query results are always translated into local time and ignore the time zone settings set in the time picker. Is a certain macro needed to do this? I gave played around with $__timeFilter() but was not able to change anything.

**What you expected to happen**:
I would expect the time column in the results to be translated into the time zone specified in the time picker

**How to reproduce it (as minimally and precisely as possible)**:
1. Import CUR dashboard
2. Change time setting to a different timezone

**Screenshots**
Grafana w/ local time
![Screen Shot 2022-07-07 at 4 27 18 PM](https://user-images.githubusercontent.com/8867000/177887959-00f8d872-6260-46eb-b4b3-d63ffe48ee91.png)

Grafana w/ UTC time
![Screen Shot 2022-07-07 at 4 27 48 PM](https://user-images.githubusercontent.com/8867000/177887978-6a1b6553-0029-4189-9efc-c87bd9045cd0.png)

Results in AWS console show correct UTC time
![Screen Shot 2022-07-07 at 4 28 00 PM](https://user-images.githubusercontent.com/8867000/177888027-a8561a11-8106-43d8-80b6-cffa84c8f99f.png)

**Environment**:
- Grafana version: v8.4.7 - in Amazon Managed Grafana
- Plugin version: 1.0.5
- User OS & Browser: Mac & Chrome

**Comment by iwysiu** [comment] 2022-07-26 21:29
Hi @robbierolin , I'm still investigating this, but is the [AT TIMEZONE](https://docs.aws.amazon.com/athena/latest/ug/athena-supported-time-zones.html) operator for Athena queries helpful?

**Comment by robbierolin** [comment] 2022-08-03 16:41
I have found that it does not change the output at all
The following gives the same result regardless of which timezone is used.

```
select
  bill_billing_period_start_date AT TIME ZONE 'US/Eastern',
  sum(line_item_blended_cost) AS cost
from $CUR_Table
where
  $__timeFilter(bill_billing_period_start_date)
group by 1
order by 1
```

**Comment by iwysiu** [comment] 2022-08-08 19:13
Hi @robbierolin , thanks for checking! Does the issue continue if you set the visualization type to `table`? I was testing it in AMG and I noticed that I had the issue when the visualization type was set to `time series` and the `table view` switch was toggled, but not when the visualization type was actually set to `table`.

**Comment by robbierolin** [comment] 2022-08-10 20:41
Hi. I see that too, when I switch the visualization type to Table it correctly displays the time zone set in the time settings. But if I turn the table view toggle on (for either visualization type), it goes back to local time.

**Comment by kylehounslow** [comment] 2022-09-08 17:50
AMG team checking in. Any results from the investigation for which a fix could be applied?

**Comment by sunker** [comment] 2022-09-09 14:24
Seems like there's a discrepancy between the behavior in the timeseries panel and the table panel. @grafana/grafana-bi-squad is that expected?

**Comment by oscarkilhed** [comment] 2022-09-09 15:09
This seems sort of similar to the behavior you get when you have no timezone specified for the data. I'm not familiar with this datasource, would it be possible to format it in a way where the timezone is included? `2022-09-09T17:08:08+02:00` or `2022-09-09T17:08:08Z` as an example

**Comment by iwysiu** [comment] 2022-09-12 15:15
@oscarkilhed the correct timezone is applied to the time series graph, but not to the table view.

**Comment by HudsonHumphries** [comment] 2022-09-29 22:53
AMG checking in, is there any progress on this issue?

**Comment by iwysiu** [comment] 2022-10-03 15:32
Hi @oscarkilhed is this considered a bug, or is the panel working as intended?

**Comment by sarahzinger** [comment] 2022-10-18 15:38
We talked about this, in a meeting recently and it sounds like:
- any customers wanting a table in their timezone should use the Table visualization and not the "table view" toggle.
- Table View is available on any panel as a preview option, to view data in a tabular format for troubleshooting panels of any type: https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/add-organize-panels/ It is meant more as a light weight debug mode, than a full visualization in and of itself. It does not currently have all the same features as our Table Panel. The Table panel is a specific type of panel that displays a data source in tabular format. https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/table/. "Table view" is for dashboard _builders_, while the "Table panel" is for dashboard _viewers_. 
- I think this is clearly a ux/docs pain point that would extend beyond the Athena Plugin, it might be worth opening a discussion in the main Grafana repo to consider if there's another way we could reframe this "Table view" or what features it needs or at least better document it's current limitations. I see for example Table views do not appear to show errors: https://github.com/grafana/grafana/discussions/46464 

All in all, I don't think this is exactly an issue with our plugin so I'm going to close this particular issue. But if I'm mistaken let me know and we can reopen! If this continues to be a pain point please open a discussion with your thoughts in the main grafana repo with how you think the Table View toggle should work, and what current limitations you see!

**Closed by sarahzinger** 2022-10-18 15:38 UTC
Labels: type/bug, datasource/Athena
