### ISSUE TITLE
Can not find a way to display data with sub-second resolution with Grafana Cloud

### ISSUE THREAD

**Issue by idea--list** [grafana/athena-datasource#226] opened 2023-03-31 20:09 UTC
**What happened**:
I am trying to display Time Series visualization with sub-second resolution using Grafana Cloud. I have the latest plugin version (v2.8.0) activated in my Grafana Cloud instance.

I am collecting MQTT messages with AWS IoT Core and routing those using Rule Engine to a Kinesis Firehose stream.
Inside Rules Engine i have setup a rule like: `SELECT *, timestamp() AS aws_timestamp, FROM 'topic_name'`
This rule simply injects a millisecond resolution timestamp telling when exactly the message has been received by AWS servers.

I can confirm sub-second resolution of my database by making a query inside AWS Athena console as well as by making the query inside my Grafana Cloud account using Table format (query in Grafana: `SELECT aint AS time, along AS value, 'test' AS metric FROM "some_db"."test" ORDER BY time ASC`)

However when i switch to Time Series format, the same query returns: "Data is missing time field"
By modifying the query to `SELECT FROM_UNIXTIME(aint/1000) AS time, along AS value, 'test' AS metric FROM "some_db"."test" ORDER BY time ASC` the Time Series get rendered, however only with second resolution. 

**What you expected to happen**:
I expected that i can render a Time Series with sub-second resolution as my data has sub-second precision.
Tried a bunch of things for 2 days now, without reaching my original goal. 

**Screenshots**
Table format confirms sub-second precision of the timestamp contained in the dataset
![image](https://user-images.githubusercontent.com/5784071/229217652-4bb2f505-0317-48ff-93f2-3283cf6e92ce.png)

Time Series format does not render using the same query
![image](https://user-images.githubusercontent.com/5784071/229218438-e2ac0073-4f64-4928-bd11-bcebf7a7abf1.png)

Time Series format can render only at second resolution using a modified query
![image](https://user-images.githubusercontent.com/5784071/229218710-ccdacb9b-246a-4926-9c11-c57f962913a5.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud
- Plugin version: 2.8.0
- OS Grafana is installed on:
- User OS & Browser: Windows 10x64, Chrome 111.0.5563.147
- Others:

**Comment by idastambuk** [comment] 2023-04-03 13:53
Hi @idea--list thanks for reporting this, I've managed to reproduce it. We're taking a look, will let you know when we have updates!

**Comment by idastambuk** [comment] 2023-04-04 11:31
Hi again @idea--list! The problem with Time Series in this case is that your column isn't a "time" column type, so our backend doesn't render it as such
Have you tried to run the query without "/1000" operation from the last screenshot? From_unixtime() returns, [from what I can see](https://trino.io/docs/current/functions/datetime.html), a timestamp(3), which should store milliseconds. If that doesn't work, is it because you're getting an error or another reason?

**Comment by idastambuk** [comment] 2023-05-09 08:09
Closing this issue as it hasn't had activity in more than 30 days

**Closed by idastambuk** 2023-05-09 08:09 UTC
Labels: type/bug, datasource/Athena
